function orderCode(){if(activeOrderCode)return activeOrderCode;const d=new Date();const p=n=>String(n).padStart(2,'0');activeOrderCode='TV'+String(d.getFullYear()).slice(2)+p(d.getMonth()+1)+p(d.getDate())+'-'+p(d.getHours())+p(d.getMinutes())+p(d.getSeconds());return activeOrderCode}
function itemSummary(item,index){return (index+1)+'. '+item.product+' / '+item.size+' / '+item.productColor+'\nText: '+item.text+'\nMiesto: '+item.position+'\nNit: '+item.threadColor+'\nPismo: '+item.font+'\nSymbol: '+item.symbol+'\nCena: '+money(item.price)}
function productionLine(item,index,code){return 'Obj. '+code+' | Polozka '+(index+1)+' | '+item.product+' | Velkost: '+item.size+' | Produkt: '+item.productColor+' | Text: '+item.text+' | '+item.position+' | Nit: '+item.threadColor+' | Pismo: '+item.font+' | Symbol: '+item.symbol+' | Cena: '+money(item.price)}
function buildPaymentText(code,total){return 'SPD*1.0*ACC:'+PAYMENT_IBAN+'*AM:'+total.toFixed(2)+'*CC:EUR*X-VS:'+code+'*RN:'+PAYMENT_ACCOUNT_NAME+'*MSG:Objednavka '+code}
function qrUrl(code,total){return 'https://api.qrserver.com/v1/create-qr-code/?size=320x320&margin=12&data='+encodeURIComponent(buildPaymentText(code,total))}
function publicItems(includePreview){
return cart.map(({signature,id,...item})=>{
const output={...item};
if(!includePreview)delete output.previewSvg;
return output;
});
}
function updateOrderForm(){
if(cart.length===0)return;const code=orderCode();const t=totals();$('#orderPreviewList').innerHTML=cart.map((item,index)=>'<div class="preview-item">'+item.previewSvg+'<div class="preview-caption">'+(index+1)+'. '+item.product+' / '+item.size+' / '+escapeHtml(item.text)+'</div></div>').join('');
$('#orderSummaryBox').textContent='Interne cislo: '+code+'\n\nPOLOZKY:\n'+cart.map(itemSummary).join('\n\n');
$('#orderTotalBox').textContent='Produkty spolu: '+money(t.items)+'\nPacketa: '+(t.shipping===0?'zdarma':money(t.shipping))+'\nPlatba: prevod na ucet vopred\nSpolu: '+money(t.total)+'\n\nPlatobne udaje, variabilny symbol a QR kod sa zobrazia az po odoslani objednavky.';
$('#itemsText').value=cart.map(itemSummary).join('\n\n');$('#itemsJson').value=JSON.stringify(publicItems(true));$('#totalInput').value=money(t.total);$('#orderCodeInput').value=code;
}
function openOrder(){ensureCart();orderSubmitted=false;$('#orderForm').style.display='block';const submit=$('#orderForm').querySelector('button[type="submit"]');if(submit)submit.disabled=false;$('#orderSuccess').classList.remove('active');updateOrderForm();$('#orderModal').hidden=false;$('#cartDrawer').classList.remove('active')}
function buildPayload(formData){
const code=orderCode();const t=totals();const production=cart.map((item,index)=>productionLine(item,index,code)).join('\n');const customer='Meno: '+(formData.get('meno')||'')+'\nEmail: '+(formData.get('email')||'')+'\nTelefon: '+(formData.get('telefon')||'');const delivery='Adresa: '+[formData.get('ulica'),formData.get('mesto'),formData.get('psc')].filter(Boolean).join(', ')+'\nPacketa: '+(formData.get('packeta')||'');const full='OBJEDNAVKA '+code+'\n\n'+customer+'\n\n'+delivery+'\n\nPOLOZKY:\n'+cart.map(itemSummary).join('\n\n')+'\n\nVYROBNY FORMAT:\n'+production+'\n\nPOLOZKY_JSON:\n'+JSON.stringify(publicItems(true))+'\n\nSPOLU:\nProdukty: '+money(t.items)+'\nPacketa: '+(t.shipping===0?'zdarma':money(t.shipping))+'\nSuma: '+money(t.total)+'\n\nPLATBA PO POTVRDENI:\nIBAN: '+PAYMENT_IBAN+'\nPrijemca: '+PAYMENT_ACCOUNT_NAME+'\nVariabilny symbol: '+code+'\nSprava pre prijemcu: Objednavka '+code+'\nQR URL: '+qrUrl(code,t.total);
return {[GOOGLE_FIELDS.interneCislo]:code,[GOOGLE_FIELDS.meno]:formData.get('meno')||'',[GOOGLE_FIELDS.email]:formData.get('email')||'',[GOOGLE_FIELDS.telefon]:formData.get('telefon')||'',[GOOGLE_FIELDS.ulica]:formData.get('ulica')||'',[GOOGLE_FIELDS.mesto]:formData.get('mesto')||'',[GOOGLE_FIELDS.psc]:formData.get('psc')||'',[GOOGLE_FIELDS.packeta]:formData.get('packeta')||'',[GOOGLE_FIELDS.polozky]:full,[GOOGLE_FIELDS.vyrobnyFormat]:production,[GOOGLE_FIELDS.pocetProduktov]:String(cart.length),[GOOGLE_FIELDS.produktySpolu]:money(t.items),[GOOGLE_FIELDS.doprava]:t.shipping===0?'Zdarma':money(t.shipping),[GOOGLE_FIELDS.platba]:'Prevod na ucet vopred',[GOOGLE_FIELDS.poplatokPlatby]:money(0),[GOOGLE_FIELDS.sumaSpolu]:money(t.total),[GOOGLE_FIELDS.poznamka]:formData.get('poznamka')||'',[GOOGLE_FIELDS.system]:'Vytvorene: '+new Date().toLocaleString('sk-SK')+'\nZdroj: tvodo.sk'};
}
function buildAppScriptPayload(formData){
const code=orderCode();const t=totals();const production=cart.map((item,index)=>productionLine(item,index,code)).join('\n');
return {interne_cislo:code,variabilny_symbol:code,meno:formData.get('meno')||'',email:formData.get('email')||'',telefon:formData.get('telefon')||'',ulica:formData.get('ulica')||'',mesto:formData.get('mesto')||'',psc:formData.get('psc')||'',packeta:formData.get('packeta')||'',poznamka:formData.get('poznamka')||'',pocet_poloziek:String(cart.length),produkty_spolu:money(t.items),doprava:t.shipping===0?'Zdarma':money(t.shipping),platba:'Prevod na ucet vopred',platba_poplatok:money(0),suma_spolu:money(t.total),polozky_text:cart.map(itemSummary).join('\n\n'),vyrobny_format:production,polozky_json:JSON.stringify(publicItems(true)),qr_url:qrUrl(code,t.total),payment_text:buildPaymentText(code,t.total),zdroj:'tvodo.sk'}
}
function nativeSubmit(payload){const form=document.createElement('form');form.method='POST';form.action=ORDER_ENDPOINT;form.target='submitFrame';form.style.display='none';Object.entries(payload).forEach(([name,value])=>{const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.appendChild(input)});document.body.appendChild(form);form.submit();setTimeout(()=>form.remove(),1000)}
function showPayment(){const code=orderCode();const t=totals();const qr=qrUrl(code,t.total);orderSubmitted=true;const paymentText='Objednavka: '+code+'\nNa uhradu: '+money(t.total)+'\nIBAN: '+PAYMENT_IBAN.replace(/(.{4})/g,'$1 ').trim()+'\nPrijemca: '+PAYMENT_ACCOUNT_NAME+'\nVariabilny symbol: '+code+'\nSprava pre prijemcu: Objednavka '+code;$('#successQrImage').src=qr;$('#successQrLink').href=qr;$('#successPaymentText').textContent=paymentText;$('#successSummaryBox').textContent='Dakujeme. Objednavku sme prijali a potvrdenie sme poslali na e-mail.\n\nPOLOZKY:\n'+cart.map(itemSummary).join('\n\n')+'\n\nSpolu na uhradu: '+money(t.total);$('#orderForm').style.display='none';$('#orderSuccess').classList.add('active')}
